.sonar_template: &sonarqube_temp
    stage: analysis
    image: ciricihq/gitlab-sonar-scanner       

stages:
    - analysis
    
sonarqube-reports:
    <<: *sonarqube_temp
    variables:
        SONAR_URL: $SONAR_HOST_URL
        SONAR_ANALYSIS_MODE: publish
        SONAR_BRANCH: $CI_COMMIT_BRANCH
        GIT_DEPTH: 0
    script:
        - gitlab-sonar-scanner -Dsonar.branch.name=$CI_COMMIT_REF_NAME